FORMAT: 1A
HOST: https://sandbox.xerpa.com.br/

# Xerpa API

Bem vindo a Xerpa _API_, nesta página você encontrará as informações
necessárias para utilizar nossa _API_. Os itens abordados nesta
pequena introdução incluem os métodos para autenticação da _API_, o
ambiente para realizar os testes das requisições e exemplos de
consultas na _API_ utilizando GraphQL.

[GraphQL](http://graphql.org/) trata-se de uma linguagem de consulta
para _APIs_ criada pelo **Facebook**, que permite obter toda a
informação em uma única solicitação, ao contrário de uma consulta de
_API_ usando _REST_, que comumente requer múltiplas interações com o
servidor.

**Referências**:
* [facebook.github.io/graphql](http://facebook.github.io/graphql/)
* [graphql.org](http://graphql.org/)

# _SANDBOX: Ambiente de Testes_

A Xerpa fornece um ambiente de testes isolado com características
semelhantes ao ambiente de produção. Este ambiente está disponível na
URL https://sandbox.xerpa.com.br. **No entanto, todos os dados criados
no ambiente de _sandbox_ são apagados após o período de uma semana**.

Também é importante ressaltar que os _tokens_ criados no _sandbox_ não
são compartilhados com o ambiente de produção e vice-versa. Portanto,
sempre que desejar utilizar este ambiente você precisa registrar uma
empresa e registrar um _token_.

Para registrar um nova empresa, acesse
https://sandbox.xerpa.com.br/company-signup e complete o processo de
registro. Depois de concluído, siga os passos a seguir para obter
acesso à API.

# Autenticação

O primeiro passo para poder utilizar a _API_ da Xerpa é solicitar um
_token_ de autenticação. Esta requisição só poderá ser realizada por
contas com credenciais de *Departamento Pessoal*.

Os passos para gerar o _token_ são descritos a seguir. No menu
principal clique em: _Configuração da Empresa > Integrações com outros
sistemas > Xerpa API_. Digite uma pequena descrição sobre o _token_ e
clique no botão *Gerar token*. **Mantenha este _token_ seguro,
considere-o como uma senha pois este _token_ permite ao usuário ler,
escrever e apagar qualquer informação associada a empresa**.

Depois de criado, cada requisição à _API_ requer um cabeçalho de
autorização no seguinte formato (lembre-se de substituir _TOKEN_ pelo
valor obtido no passo anterior):

```
  Authorization: Bearer TOKEN
```

# Política de depreciação

Nossa _API_ ainda não está completa e por isso está em constante
mudança. A maior parte das alterações adiciona campos, o que
geralmente não requer nenhuma mudança de código dos usuários da _API_.

Nos casos que a mudança quebra o contrato, removendo ou modificando um
campo, ela é feita um duas fases. O novo campo é adicionado e o campo
antigo é marcado como _deprecated_. Eles coexistem por um período de
no mínimo 3 meses, após este período o campo _deprecated_ é
removido. A ideia é permitir que usuários tenham tempo para ajustar o
código que dependa de campos descontinuados.

Campos marcados como _deprecated_ não aparecem na documentação da API
porém continuam funcionando normalmente. O _API Playground_ permite
inspecionar o _schema_ e identificar os campos marcados como
_deprecated_ bem como a sua documentação, caso exista.

Ainda não existe nenhum mecanismo formal de notificação caso o usuário
da API esteja usando campos descontinuados.  Hoje a única ferramenta
disponível é inspecionar manualmente `_API Playground_` ou fazendo
[solicitações de
introspecção](http://graphql.org/learn/introspection/) para a _API_.

# Api Playground

[API Playground](https://sandbox.xerpa.com.br/api/playground) é uma
instância do [graphiql](https://github.com/graphql/graphiql) que
funciona como uma ferramenta interativa no navegador para explorar uma
_API GraphQL_. Com essa ferramenta é possível testar suas solicitações
de maneira interativa e navegar pela estrutura da _API_.

Todos os exemplos nessa documentação podem ser usados no
_playground_. Para isso copie a soliticação juntamente com as
variáveis para os locais apropriados no _graphiql_.

## GraphQL API [/api/g{?variables}]

### Profile [POST]

Dados de perfil

- Parameters
    - variables: `{"profile_id": "1"}` (json, required)

+ Request (application/graphql)

    + Headers

            authorization: Bearer TOKEN

    + Body

            query($profile_id: ID!) {
              profile(id: $profile_id) {
                id, name
              }
            }

+ Response 200 (application/json)

    + Body

            {
                "data": {
                    "profile": {
                        "id": "1",
                        "name": "Tenzing Norgay"
                    }
                }
            }

    + Attributes
        + profile: (Profile)

### Company [POST]

Dados da empresa

- Parameters
    - variables: `{"company_id": "1"}` (json, required)

+ Request (application/graphql)

    + Headers

            authorization: Bearer TOKEN

    + Body

            query($company_id: ID!) {
              company(id: $company_id) {
                id, name
              }
            }

+ Response 200 (application/json)

    + Body

            {
                "data": {
                    "company": {
                        "id": "1",
                        "name": "Xerpa"
                    }
                }
            }

    + Attributes
        + company: (Company)

### RawAfdEntries [POST]

Busca entradas de ponto originais vindas do arquivo AFD (Arquivo
Fonte de Dados) dentro de um período para os PIS informados.

A diferença em dias entre o começo e o final do período não deve
ultrapassar 31 dias corridos.

- Parameters
    - variables: `{"company_id": "company:86ce5f40-8e9c-11e8-8d49-0242ac1a0007", "pis_list": ["97651815781"], "start_on": "2018-01-05", "end_on": "2018-01-06"}` (json, required)

+ Request (application/graphql)

    + Headers

            authorization: Bearer TOKEN

    + Body

            query($company_id: ID!, $pis_list: [String!]!, $start_on: Date!, $end_on: Date!) {
              rawAfdEntries(company_id: $company_id, pis_list: $pis_list, start_on: $start_on, end_on: $end_on) {
                pis
                datetime
              }
            }

+ Response 200 (application/json)

    + Body

            {
              "data": {
                "rawAfdEntries": [
                  {
                    "pis": "97651815781",
                    "datetime": "2018-01-05T09:00:00.000000"
                  },
                  {
                    "pis": "97651815781",
                    "datetime": "2018-01-05T12:00:00.000000"
                  },
                  {
                    "pis": "97651815781",
                    "datetime": "2018-01-05T13:00:00.000000"
                  },
                  {
                    "pis": "97651815781",
                    "datetime": "2018-01-05T18:00:00.000000"
                  },
                  {
                    "pis": "97651815781",
                    "datetime": "2018-01-06T09:00:00.000000"
                  },
                  {
                    "pis": "97651815781",
                    "datetime": "2018-01-06T12:00:00.000000"
                  },
                  {
                    "pis": "97651815781",
                    "datetime": "2018-01-06T13:00:00.000000"
                  },
                  {
                    "pis": "97651815781",
                    "datetime": "2018-01-06T18:00:00.000000"
                  }
                ]
              }
            }

    + Attributes
        + rawAfdEntry: (RawAfdEntry)

# Data Structures

## DimepKairosCompanyExternalAssociations (object)

+ password (string)
+ username (string)


## DocumentMaritalStatusAttachments (object)

+ front_image (Attachment)


## ProfileTransport (object)

+ card_description (string)
+ description (string)
+ status (string)
+ total_cost (string) -- money
+ type (string)


## UploadUrl (object)

+ raw_url (string)
+ read_url (string)
+ url (string)
+ write_url (string)


## BankAccountUpsertPayload (object)

+ bank_account (BankAccount)
+ profile (Profile)


## Contents (object)

+ texts (string)
+ title (string)


## Workload (object)

+ company (object) -- Company
+ external_associations (ExternalAssociations)
+ id (string) -- id
+ name (string)
+ schedule (WorkloadSchedule)
+ type (string)


## VerificationCode (object)

+ contact_id (string) -- id
+ profile (Profile)


## DanglingPis (object)

+ pagination_token (string) -- id
+ pis (string) -- id


## DateTime (object)

+ date (string) -- date
+ time (string) -- time


## TokenDescription (object)

+ company (object) -- Company
+ description (string)
+ id (string) -- id
+ inserted_at (string) -- naivedatetime


## Company (object)

+ viewer_can_view_offboardings (boolean)
+ id (string) -- id
+ positions (Position)
+ viewer_can_view_work_periods (boolean)
+ profile_search_aggregation (SearchAggregation)
+ has_automatic_time_clock_import (boolean)
+ last_timeclock_import (string) -- naivedatetime
+ viewer_can_view_statistics (boolean)
+ viewer_can_view_absences (boolean)
+ viewer_can_view_paystubs (boolean)
+ viewer_can_census (boolean)
+ custom_fields (CustomField)
+ work_period (WorkPeriod)
+ business_units (BusinessUnit)
+ viewer_can_administer (boolean)
+ external_associations (CompanyExternalAssociations)
+ viewer_can_view_billing (boolean)
+ offices (Office)
+ kits (Kit)
+ has_sent_paystubs (boolean)
+ work_period_config (WorkPeriodConfig)
+ profile_search (ProfileSearchResult)
+ unions (Union)
+ integrations (object)
+ guid (string) -- id
+ viewer_can_view_onboardings (boolean)
+ work_periods (WorkPeriodListView)
+ department (Department)
+ statistics (Statistics)
+ customization (CompanyCustomization)
+ integration_export (DefaultIntegrationExport)
+ viewer_can_view_dashboards (boolean)
+ departments (Department)
+ paystub_capabilities (PaystubCapabilityInfo)
+ cost_centers (CostCenter)
+ viewer_can_view_vacations (boolean)
+ billing (Billing)
+ viewer_can_invite (boolean)
+ custom_documents (CustomDocument)
+ workloads (Workload)
+ is_accountant (boolean)
+ custom_integration_export (CustomIntegrationExport)
+ name (string)
+ viewer_can_view_users (boolean)
+ api_tokens (TokenDescription)
+ benefits (CompanyBenefits)
+ viewer_can_import (boolean)


## Union (object)

+ abbreviation (string)
+ external_associations (ExternalAssociations)
+ id (string) -- id
+ name (string)


## Voter (object)

+ attachments (VoterAttachments)
+ number (string)
+ scan_date (string) -- date
+ scanned_fields (string)
+ section (string)
+ zone (string)


## DisabilitiesDescription (object)

+ label (string)
+ name (string)
+ value (string)


## WorkdayEntry (object)

+ date (string) -- date
+ edit_reason (string)
+ id (string) -- id
+ time (string) -- time
+ type (string)


## PersonalAddressAttachments (object)

+ proof_of_address (Attachment)


## Scale (object)

+ days (Day)
+ end_date (string) -- date
+ id (string) -- id
+ pis (string)
+ start_date (string) -- date


## PaymentMethodDescription (object)

+ label (string)
+ name (string)
+ value (string)


## Position (object)

+ id (string) -- id
+ levels (PositionLevel)
+ name (string)


## UploadDeleteReply (object)

+ object_id (string)


## PdfAttachment (object)

+ aspect (number)
+ etag (string)
+ id (string)
+ mime (string)
+ mtime (string) -- datetime
+ name (string)
+ pages (number)
+ type (string)
+ url (string)


## MutatePositionReply (object)

+ errors (Error)
+ positions (Position)


## ValidateImagePayload (object)

+ signed_url (string)


## WorkdayHistoryActionDescription (object)

+ label (string)
+ name (string)
+ value (string)


## DocumentCnhVerificationState (object)

+ category (string)
+ expiration_date (string)
+ issue_date (string)
+ number (string)


## Transport (object)

+ id (string) -- id
+ name (string)
+ type (string)


## ProfileStatusDescription (object)

+ label (string)
+ name (string)
+ value (string)


## Profile (object)

+ viewer_can_delete_profile (boolean)
+ workload (Workload)
+ qualification_status (string)
+ union (Union)
+ qualification_date (string) -- date
+ access_situation (string)
+ transport (ProfileTransport)
+ messages (Message)
+ marital_status (string)
+ position_level (PositionLevel)
+ viewer_can_reinvite_profile (boolean)
+ id (string) -- id
+ viewer_can_block_profile (boolean)
+ personal_contact (PersonalContact)
+ viewer_can_approve_absence (boolean)
+ admission_date (string) -- date
+ viewer_can_edit_contract (boolean)
+ cost_center (CostCenter)
+ business_unit (BusinessUnit)
+ emergency_contact (EmergencyContact)
+ viewer_can_edit_profile_status (boolean)
+ absence (Absence)
+ absences (Absence)
+ life_insurance (ProfileLifeInsurance)
+ employee_number (string)
+ custom_fields (CustomField)
+ viewer_can_edit_salary (boolean)
+ phone (ProfilePhone)
+ gender (string)
+ work_period (ProfileWorkPeriod)
+ invite (Invite)
+ personal_address (PersonalAddress)
+ preferred_name (string)
+ health_insurance (ProfileHealthInsurance)
+ probation_date1 (string) -- date
+ viewer_can_view_xerpay (boolean)
+ contact_preferences (ContactPreference)
+ child_care (ProfileChildCare)
+ office (Office)
+ custom_document_submissions (CustomDocumentSubmission)
+ notification_contacts (Contact)
+ mothers_name (string)
+ education (Education)
+ probation_date2 (string) -- date
+ probation_periods (string)
+ disabilities (string)
+ salary_period (string)
+ dental_insurance (ProfileDentalInsurance)
+ trusted_position (boolean)
+ last_day (string) -- date
+ cbo (Cbo)
+ offboard (Offboard)
+ guid (string) -- id
+ fallback_contact (string)
+ meal_allowance (ProfileMealAllowance)
+ salary (string) -- money
+ username (string)
+ naturality_city (City)
+ work_periods (ProfileWorkPeriodListView)
+ department (Department)
+ overtime_allowed (boolean)
+ viewer_can_notify_dp (boolean)
+ viewer_can_view_offboard_profile (boolean)
+ punchcard_required (boolean)
+ managers (PublicProfile)
+ onboarding (Onboarding)
+ employment_contract (string)
+ fathers_name (string)
+ documents (ProfileDocuments)
+ viewer_can_view_salary (boolean)
+ avatar (Thumbnail)
+ notification_date (string) -- date
+ viewer_can_notify_accountant (boolean)
+ skin_color (string)
+ business_contact (BusinessContact)
+ account (Account)
+ subordinates (PublicProfile)
+ birthday (string) -- date
+ name (string)
+ status (string)
+ bank_accounts (BankAccount)
+ nationality (string)


## EmploymentContractDescription (object)

+ label (string)
+ name (string)
+ value (string)


## WorkloadBoundaries (object)

+ end_date (string) -- naivedatetime
+ start_date (string) -- naivedatetime


## Address (object)

+ address1 (string)
+ address2 (string)
+ addrtype (string)
+ city (City)
+ city_id (string) -- id
+ district (string)
+ id (string) -- id
+ number (string)
+ zipcode (string)


## DocumentCamUpsertPayload (object)

+ cam (object)
+ profile (Profile)


## PositionLevel (object)

+ external_associations (ExternalAssociations)
+ id (string) -- id
+ name (string)
+ position (Position)


## KenobyIntegration (object)

+ active (boolean)
+ associable_fields (IntegrationField)
+ company (Company)
+ counts (IntegrationCount)
+ description (string)
+ fields (IntegrationField)
+ name (string)
+ token (Token)
+ type (string)


## DefaultIntegrationExport (object)

+ dependents_file_path (string)
+ file_path (string)
+ id (string) -- id
+ incomplete_profiles (IncompleteProfile)
+ integration (object)
+ non_exportable_profiles (Profile)
+ profiles (Profile)
+ renapse_bank_file_path (string)


## Bank (object)

+ code (string)
+ id (string) -- id
+ name (string)


## Day (object)

+ adjustment_entries (AdjustmentEntries)
+ date (string) -- date
+ original_entries (OriginalEntries)
+ types (string)


## DocumentCnhOcrRequestPayload (object)

+ ok (boolean)


## ProfileMissingLastDay (object)

+ pagination_token (string) -- id
+ profile (Profile)


## PersonalContact (object)

+ email (string)
+ emergency (EmergencyContact)
+ mobile (string)
+ phone (string)
+ profile (object) -- Profile
+ updated_contacts (string)


## DocumentCnhOcrProgressPayload (object)

+ cnh (DocumentCnh)


## DocumentMaritalStatusCertificate (object)

+ attachments (DocumentMaritalStatusAttachments)
+ marital_status (string)
+ nonexistent (boolean)


## WorkPeriodListOverview (object)

+ profiles_count (number)
+ profiles_with_absences_count (number)


## CustomIntegrationField (object)

+ category (CustomIntegrationFieldCategory)
+ name (string)
+ selected (boolean)
+ type (string)


## CostCenter (object)

+ external_associations (ExternalAssociations)
+ id (string) -- id
+ name (string)


## PaystubCapabilityInfo (object)

+ capability (string)
+ enabled (boolean)


## BusinessUnit (object)

+ external_associations (ExternalAssociations)
+ id (string) -- id
+ name (string)


## TransportTypeDescription (object)

+ label (string)
+ name (string)
+ value (string)


## DocumentCnhAttachments (object)

+ front_image (Attachment)


## PaystubCapabilityDescription (object)

+ label (string)
+ name (string)
+ value (string)


## EmergencyContact (object)

+ name (string)
+ phone (string)
+ relationship (string)


## DocumentRgAttachments (object)

+ back_image (Attachment)
+ front_image (Attachment)


## PublicPositionLevel (object)

+ id (string) -- id
+ name (string)
+ position (PublicPosition)


## TurnoverResult (object)

+ value (number)


## SkinColorDescription (object)

+ label (string)
+ name (string)
+ value (string)


## MissingProfiles (object)

+ results (DanglingPis)
+ total_hits (number)


## DocumentRgVerificationState (object)

+ issue_date (string)
+ issuer (string)
+ number (string)
+ state_id (string)


## City (object)

+ id (string) -- id
+ name (string)
+ state (State)


## PaystubStatisticValue (object)

+ entry (Identifier)
+ value (number)


## JourneyFixedConfig (object)

+ entries (DateTimeEntry)
+ id (string) -- id


## Identifier (object)

+ key (string) -- id
+ label (string)


## Absence (object)

+ attachment (Attachment)
+ comments (Thread)
+ description (string)
+ duration_in_minutes (number)
+ finish_date (string) -- date
+ finish_time (string) -- time
+ guid (string) -- id
+ id (string) -- id
+ profile (object) -- Profile
+ start_date (string) -- date
+ start_time (string) -- time
+ status (string)
+ type (string)
+ viewer_can_change_status (boolean)
+ viewer_can_edit (boolean)


## JourneyTemplate (object)

+ day0 (object)
+ day1 (object)
+ day2 (object)
+ day3 (object)
+ day4 (object)
+ day5 (object)
+ day6 (object)
+ group_id (string) -- id
+ id (string) -- id
+ name (string)
+ type (string)


## WorkPeriodSubscriptionOverviewByDepartment (object)

+ department (Department)
+ overview (WorkPeriodSubscriptionOverview)
+ summaries (WorkPeriodSubscriptionProfile)


## Comment (object)

+ author (PublicProfile)
+ id (string) -- id
+ inserted_at (string) -- datetime
+ message (string)
+ thread (Thread)


## LifeInsurance (object)

+ id (string) -- id
+ name (string)
+ plan (string)
+ provider (string)


## MealAllowanceDiscountDescription (object)

+ label (string)
+ name (string)
+ value (string)


## WorkloadTypeDescription (object)

+ label (string)
+ name (string)
+ value (string)


## AvatarPayload (object)

+ profile (Profile)


## DocumentPisAttachments (object)

+ front_image (Attachment)


## IntegrationCount (object)

+ associated (number)
+ total (number)


## ProfileWorkPeriodListView (object)

+ end_on (string) -- date
+ id (string) -- id
+ start_on (string) -- date


## SearchAggregationCount (object)

+ count (number)
+ value (string)


## CustomDocumentSubmissionsInsertPayload (object)

+ profiles (Profile)


## DocumentCam (object)

+ attachments (DocumentCamAttachments)
+ number (string)
+ scan_date (string) -- date
+ scanned_fields (string)


## Kit (object)

+ custom_documents (CustomDocument)
+ id (string) -- id
+ name (string)


## Role (object)

+ access (string)
+ company (Company)


## Payment (object)

+ method (string)
+ next_payment_due (string) -- date


## PaymentBoleto (object)

+ due (string) -- date
+ number (string)
+ status (string)
+ url (string)


## PaystubStatisticDataset (object)

+ department_id (string)
+ values (PaystubStatisticValue)
+ year_month (YearMonth)


## WorkPeriod (object)

+ acjef_path (string)
+ afdt_path (string)
+ all_attendance_records_signed (boolean)
+ archived_on (string) -- date
+ can_be_closed (boolean)
+ closed_on (string) -- date
+ department (object)
+ departments_overview (WorkPeriodOverviewByDepartment)
+ end_on (string) -- date
+ filter (FilteredWorkPeriod)
+ generating_attendance_records (boolean)
+ id (string) -- id
+ manager (object)
+ managers_overview (WorkPeriodOverviewByManager)
+ profile_count (number)
+ raw_attendance_records_object_ids_by_department (string)
+ raw_attendance_records_object_ids_by_manager (string)
+ signature_count (number)
+ signatures (SignatureResult)
+ start_on (string) -- date
+ status (string)
+ time_summary_path (string)
+ viewer_can_archive (boolean)
+ viewer_can_close (boolean)
+ viewer_can_download_treatment_files (boolean)


## WorkloadDescriptionPeriod (object)

+ checkin (string) -- time
+ checkout (string) -- time


## ProfileWorkPeriod (object)

+ archived_on (string) -- date
+ end_on (string) -- date
+ id (string) -- id
+ overview (ProfileWorkPeriodOverview)
+ signature (WorkPeriodProfile)
+ start_on (string) -- date
+ status (string)
+ workdays (Workday)


## DocumentSusUpsertPayload (object)

+ profile (Profile)
+ sus (object)


## SearchAggregation (object)

+ counts (SearchAggregationCount)
+ field_name (string)


## Invite (object)

+ status (string)


## ProfileIdentificationUpdatePayload (object)

+ profile (Profile)


## ProfileHealthInsurance (object)

+ chosen (HealthInsurance)
+ status (string)


## PersonalAddress (object)

+ address1 (string)
+ address2 (string)
+ attachments (PersonalAddressAttachments)
+ city (City)
+ district (string)
+ number (string)
+ type (string)
+ zipcode (string)


## ProfileQualificationDataPayload (object)

+ profile (Profile)


## NotificationTopicTypeDescription (object)

+ label (string)
+ name (string)
+ value (string)


## AdjustmentEntries (object)

+ datetime (string) -- naivedatetime


## HealthInsurance (object)

+ id (string) -- id
+ name (string)
+ plan (string)
+ provider (string)


## PublicProfile (object)

+ avatar (Thumbnail)
+ id (string) -- id
+ name (string)
+ position_level (PublicPositionLevel)


## TimeClockImportFileOverview (object)

+ entries_count (number)
+ entries_end_on (string) -- date
+ entries_start_on (string) -- date
+ profiles_not_found_count (number)
+ time_clock (TimeClock)


## CustomDocument (object)

+ attachment (Attachment)
+ id (string) -- id
+ name (string)


## BankAccountTypeDescription (object)

+ label (string)
+ name (string)
+ value (string)


## MessageUpsertPayload (object)

+ profile (Profile)


## ProfileDocuments (object)

+ cam (object)
+ cnh (object)
+ cpf (DocumentCpf)
+ marital_status_certificate (object)
+ pis (object)
+ rg (DocumentRg)
+ rne (DocumentRne)
+ sus (object)
+ voter (object)


## ExternalAssociations (object)

+ custom (string)
+ dominio (string)
+ totvs_rm_labore (string)


## ProfileDentalInsurance (object)

+ chosen (DentalInsurance)
+ status (string)


## MealAllowancePeriodicityDescription (object)

+ label (string)
+ name (string)
+ value (string)


## PaymentStatusDescription (object)

+ label (string)
+ name (string)
+ value (string)


## ErrorMessage (object)

+ description (string)
+ title (string)


## ChildCare (object)

+ discount_percentage (number)
+ id (string) -- id
+ name (string)


## WorkdayEntryTypeDescription (object)

+ label (string)
+ name (string)
+ value (string)


## BitmapAttachment (object)

+ etag (string)
+ height (number)
+ id (string)
+ mime (string)
+ mtime (string) -- datetime
+ name (string)
+ type (string)
+ url (string)
+ width (number)


## AbsenceTypeDescription (object)

+ label (string)
+ name (string)
+ value (string)


## VoterAttachments (object)

+ front_image (Attachment)


## DocumentSus (object)

+ attachments (DocumentSusAttachments)
+ number (string)
+ scan_date (string) -- date
+ scanned_fields (string)


## GenderDescription (object)

+ label (string)
+ name (string)
+ value (string)


## Office (object)

+ address (Address)
+ company (object) -- Company
+ external_associations (ExternalAssociations)
+ id (string) -- id
+ name (string)


## TimeClockImportResult (object)

+ id (string) -- id
+ import_file_overview (TimeClockImportFileOverview)
+ pending (boolean)
+ profiles_not_found_count (number)


## Viewer (object)

+ profile (Profile)


## DayTypeDescription (object)

+ label (string)
+ name (string)
+ value (string)


## CustomIntegrationFieldCategory (object)

+ name (string)
+ type (string)


## BankAccount (object)

+ account (string)
+ account_type (string)
+ agency (string)
+ id (string) -- id


## DocumentCpfVerificationState (object)

+ number (string)


## Education (object)

+ attachments (EducationAttachments)
+ conclusion (string) -- date
+ country (string)
+ degree (string)
+ duration (string)
+ field (string)
+ id (string) -- id
+ school (string)
+ situation (string)
+ state (string)


## EducationUpsertPayload (object)

+ education (Education)
+ profile (Profile)


## Steps (object)

+ contents (Contents)
+ title (string)


## Message (object)

+ can_dismiss (boolean)
+ checked_at (string) -- datetime
+ content (string)
+ errors (ErrorMessage)
+ id (string) -- id
+ step_by_step (StepMessage)
+ subtitle (string)
+ title (string)
+ type (string)


## ExpectedEntry (object)

+ date (string) -- date
+ time (string) -- time


## RootMutationType (object)

+ workload (Workload)
+ workday_adjust (Workday)
+ union (Union)
+ personal_address_upsert (PersonalAddressUpsertPayload)
+ comment_insert (Comment)
+ invite_profiles (Profile)
+ validate_image (ValidateImagePayload)
+ dismiss_message_upsert (MessageUpsertPayload)
+ personal_contact (PersonalContact)
+ document_cpf_upsert (DocumentCpfUpsertPayload)
+ document_cnh_ocr_request (DocumentCnhOcrRequestPayload)
+ cost_center (CostCenter)
+ business_unit (BusinessUnit)
+ time_clock_import_create (TimeClockImportResult)
+ document_cam_upsert (DocumentCamUpsertPayload)
+ journey_template_delete (JourneyTemplate)
+ upload_delete (UploadDeleteReply)
+ journey_template_upsert (JourneyTemplate)
+ document_rg_upsert (DocumentRgUpsertPayload)
+ absence (Absence)
+ complete_profile_information (WorkPeriodConfig)
+ profile_custom_fields_assoc (ProfileCustomFieldsAssocPayload)
+ profile_contract_update (Profile)
+ document_marital_status_upsert (DocumentMaritalStatusUpsertPayload)
+ office_delete (Office)
+ document_cnh_upsert (DocumentCnhUpsertPayload)
+ profile_census (Profile)
+ set_last_day (WorkPeriodConfig)
+ document_cnh_ocr_upsert (DocumentCnhUpsertPayload)
+ contact_preference_delete (ContactPreference)
+ document_voter_upsert (DocumentVoterUpsertPayload)
+ workload_delete (Workload)
+ office (Office)
+ create_company_integration (object)
+ profile_qualification_data_upsert (ProfileQualificationDataPayload)
+ reset_vacations (Company)
+ absence_delete (Absence)
+ custom_document_submissions_insert (CustomDocumentSubmissionsInsertPayload)
+ work_period_profile_signatures (WorkPeriodProfile)
+ api_token_delete (TokenDescription)
+ alter_positions (MutatePositionReply)
+ document_rg_ocr_request (DocumentRgOcrRequestPayload)
+ grant_access (Profile)
+ delete_company_integration (Company)
+ token_delete (Token)
+ request_contact_verification_code (VerificationCode)
+ comment_delete (Comment)
+ make_accountant (Company)
+ make_paying_company (Company)
+ change_username (Profile)
+ profile_identification_update (ProfileIdentificationUpdatePayload)
+ api_token_generate (ApiToken)
+ contact_preference (ContactPreference)
+ department (Department)
+ reset_profile_vacation (Profile)
+ set_paystub_capability (Company)
+ integration_export (DefaultIntegrationExport)
+ upload_begin (UploadInfo)
+ bank_account_upsert (BankAccountUpsertPayload)
+ document_cpf_ocr_upsert (DocumentCpfUpsertPayload)
+ upload_done (Attachment)
+ time_clock_import_commit (TimeClockImportResult)
+ update_company (Company)
+ avatar_upsert (AvatarPayload)
+ manual_invite_profiles (Profile)
+ education_upsert (EducationUpsertPayload)
+ work_period_accept_all (WorkPeriodAcceptAllReply)
+ set_company_plan (Company)
+ work_period_archive (WorkPeriod)
+ set_company_customization (Company)
+ contact_verification (Contact)
+ bank_account_delete (BankAccountUpsertPayload)
+ business_contact (BusinessContact)
+ delete_paystub_file_page (PaystubFilePage)
+ update_external_associations (object)
+ document_sus_upsert (DocumentSusUpsertPayload)
+ custom_integration_export (CustomIntegrationExport)
+ generate_upload_url (UploadUrl)
+ custom_integration (CustomCompanyIntegration)
+ token_generate (Token)
+ document_rg_ocr_upsert (DocumentRgUpsertPayload)
+ work_period_close (WorkPeriod)
+ work_period_profile_config (WorkPeriodConfig)


## RootSubscriptionType (object)

+ document_cnh_ocr_progress (DocumentCnhOcrProgressPayload)
+ document_rg_cpf_ocr_progress (DocumentRgCpfOcrProgressPayload)
+ generating_attendance_records (Progress)
+ work_period_overview (WorkPeriodSubscriptionOverviewWithSummaries)
+ work_period_overview_by_department (WorkPeriodSubscriptionOverviewByDepartment)
+ work_period_overview_by_manager (WorkPeriodSubscriptionOverviewByManager)
+ work_period_profile_overview (WorkPeriodSubscriptionProfile)


## ProfileLifeInsurance (object)

+ chosen (LifeInsurance)
+ status (string)


## SalaryPeriodDescription (object)

+ label (string)
+ name (string)
+ value (string)


## ProfileSearchResult (object)

+ all_guids (string) -- id
+ profiles (Profile)
+ total_hits (number)


## WorkPeriodConfig (object)

+ incomplete_profiles (IncompleteProfiles)
+ missing_profiles (MissingProfiles)
+ profiles_missing_last_day (ProfilesMissingLastDay)


## FilteredWorkPeriod (object)

+ overview (WorkPeriodOverview)
+ treatment (WorkPeriodFilterResults)


## ProbationPeriodsDescription (object)

+ label (string)
+ name (string)
+ value (string)


## WorkloadSchedule (object)

+ description (WorkloadDescription)
+ load_in_minutes (number)
+ nuclear_descriptions (WorkloadNuclearDescription)
+ regimen (string)


## EntriesSummaryEntryPair (object)

+ in (WorkdayEntry)
+ out (WorkdayEntry)


## DocumentCnh (object)

+ attachments (DocumentCnhAttachments)
+ category (string)
+ expiration_date (string) -- date
+ is_validation_ongoing (boolean)
+ issue_date (string) -- date
+ nonexistent (boolean)
+ number (string)
+ scan_date (string) -- date
+ scanned_fields (string)
+ verification_state (DocumentCnhVerificationState)


## CustomDocumentSubmissionDeliveryTypeDescription (object)

+ label (string)
+ name (string)
+ value (string)


## DentalInsurance (object)

+ id (string) -- id
+ name (string)
+ plan (string)
+ provider (string)
+ total_cost (string) -- money


## PaystubStatistics (object)

+ available_departments (Identifier)
+ dataset (PaystubStatisticDataset)
+ year_month_bounds (YearMonth)


## MealAllowanceTypeDescription (object)

+ label (string)
+ name (string)
+ value (string)


## DocumentVoterUpsertPayload (object)

+ profile (Profile)
+ voter (object)


## DocumentCpfUpsertPayload (object)

+ cpf (DocumentCpf)
+ profile (Profile)


## WorkPeriodSubscriptionProfile (object)

+ profile_id (string) -- id
+ time_balance_in_minutes (number)


## WorkPeriodOverview (object)

+ profiles_count (number)
+ profiles_done_count (number)
+ profiles_on_offboard_count (number)
+ profiles_on_vacation_count (number)
+ profiles_pending_count (number)
+ profiles_with_absences_done_count (number)
+ profiles_with_absences_pending_count (number)
+ profiles_with_workdays_done_count (number)
+ profiles_with_workdays_pending_count (number)
+ time_balance_in_minutes (number)


## DocumentRne (object)

+ attachments (DocumentRneAttachments)
+ class (string)
+ entry_date (string) -- date
+ expiration (string) -- date
+ issue_date (string) -- date
+ issuer (string)
+ number (string)
+ scan_date (string) -- date
+ scanned_fields (string)


## EntryPosition (object)

+ entries (WorkdayEntry)
+ expected (ExpectedEntry)


## Cbo (object)

+ code (string)
+ id (string) -- id
+ name (string)


## PersonalAddressUpsertPayload (object)

+ personal_address (PersonalAddress)
+ profile (Profile)


## DocumentRneAttachments (object)

+ rne_front (Attachment)


## StreetTypeDescription (object)

+ label (string)
+ name (string)
+ value (string)


## Offboard (object)

+ other_attachments (object)
+ payment_attachments (object)


## AccessLevelDescription (object)

+ label (string)
+ name (string)
+ value (string)


## IncompleteProfile (object)

+ incomplete_fields (string)
+ profile (Profile)


## EnumAggregation (object)

+ bucket (Identifier)
+ count (number)


## WorkloadDescription (object)

+ id (string) -- id
+ periods (WorkloadDescriptionPeriod)
+ weekdays (string)


## EnumDescriptions (object)

+ absence_type (AbsenceTypeDescription)
+ marital_status (MaritalStatusDescription)
+ street_type (StreetTypeDescription)
+ absence_status (AbsenceStatusDescription)
+ weekday (WeekdayDescription)
+ workday_history_action (WorkdayHistoryActionDescription)
+ contact_type (ContactTypeDescription)
+ workload_type (WorkloadTypeDescription)
+ bank_account_type (BankAccountTypeDescription)
+ template_day_type (TemplateDayTypeDescription)
+ gender (GenderDescription)
+ profile_status (ProfileStatusDescription)
+ access_level (AccessLevelDescription)
+ workday_entry_type (WorkdayEntryTypeDescription)
+ paystub_capability (PaystubCapabilityDescription)
+ probation_periods (ProbationPeriodsDescription)
+ disabilities (DisabilitiesDescription)
+ meal_allowance_periodicity (MealAllowancePeriodicityDescription)
+ salary_period (SalaryPeriodDescription)
+ meal_allowance_discount (MealAllowanceDiscountDescription)
+ xerpa_plan (XerpaPlanDescription)
+ workday_status (WorkdayStatusDescription)
+ custom_document_submission_status (CustomDocumentSubmissionStatusDescription)
+ work_period_status (WorkPeriodStatusDescription)
+ transport_type (TransportTypeDescription)
+ notification_topic_type (NotificationTopicTypeDescription)
+ profile_benefit_status (ProfileBenefitStatusDescription)
+ profile_access_situation (ProfileAccessSituationDescription)
+ payment_method (PaymentMethodDescription)
+ notification_contact_label (string)
+ employment_contract (EmploymentContractDescription)
+ day_type (DayTypeDescription)
+ custom_document_submission_delivery_type (CustomDocumentSubmissionDeliveryTypeDescription)
+ verification_status (VerificationStatusDescription)
+ skin_color (SkinColorDescription)
+ meal_allowance_type (MealAllowanceTypeDescription)
+ custom_document_submission_sending_type (CustomDocumentSubmissionSendingTypeDescription)
+ nationality (NationalityDescription)
+ payment_status (PaymentStatusDescription)


## CompanyCustomization (object)

+ cover_image_url (string)
+ login_background_image_url (string)
+ logo_image_url (string)
+ primary_color (string)
+ secondary_color (string)


## MealAllowance (object)

+ amount (string) -- money
+ discount_amount (string) -- money
+ discount_type (string)
+ id (string) -- id
+ name (string)
+ periodicity (string)
+ provider (MealAllowanceProvider)
+ type (string)


## Constant (object)

+ code (string)
+ label (string)
+ name (string)


## DocumentRgOcrRequestPayload (object)

+ ok (boolean)


## DefaultCompanyIntegration (object)

+ active (boolean)
+ associable_fields (IntegrationField)
+ company (Company)
+ counts (IntegrationCount)
+ description (string)
+ fields (IntegrationField)
+ name (string)
+ type (string)


## DocumentSusAttachments (object)

+ back_image (Attachment)


## WorkPeriodOverviewByDepartment (object)

+ department (object)
+ overview (WorkPeriodOverview)


## ApiToken (object)

+ company (Company)
+ description (string)
+ id (string) -- id
+ inserted_at (string) -- naivedatetime
+ token (string)


## WorkPeriodProfile (object)

+ is_signed (boolean)
+ profile (Profile)
+ raw_attendance_record_attachment (Attachment)
+ signed_attendance_record_attachment (Attachment)


## DocumentCpf (object)

+ attachments (DocumentCpfAttachments)
+ is_validation_ongoing (boolean)
+ number (string)
+ scan_date (string) -- date
+ scanned_fields (string)
+ verification_state (DocumentCpfVerificationState)


## ContactPreference (object)

+ contact (Contact)
+ id (string) -- id
+ topic (string)


## Department (object)

+ external_associations (ExternalAssociations)
+ id (string) -- id
+ name (string)


## Statistics (object)

+ headcount (Headcount)
+ paystub (PaystubStatistics)
+ turnover (Turnover)
+ year_month_bounds (YearMonth)


## Period (object)

+ end_date (string) -- date
+ group_id (string)
+ id (string) -- id
+ profiles_count (number)
+ profiles_with_absences_count (number)
+ scales (Scale)
+ start_date (string) -- date
+ status (string)


## Thumbnail (object)

+ url (string)


## Thread (object)

+ id (string) -- id
+ messages (Comment)


## EntriesSummary (object)

+ disregarded_entries (WorkdayEntry)
+ entry_pairs (EntriesSummaryEntryPair)


## DominioCompanyExternalAssociations (object)

+ branch (string)
+ id (string)
+ service (string)
+ simples (string)


## ProfilesMissingLastDay (object)

+ results (ProfileMissingLastDay)
+ total_hits (number)


## WorkPeriodOverviewByManager (object)

+ manager (object)
+ overview (WorkPeriodOverview)


## WorkdayStatusDescription (object)

+ label (string)
+ name (string)
+ value (string)


## WorkPeriodIncompleteProfile (object)

+ pagination_token (string) -- id
+ profile (Profile)


## CustomField (object)

+ id (string) -- id
+ name (string)


## WorkdayWorkload (object)

+ load_in_minutes (number)
+ periods (WorkloadDescriptionPeriod)
+ regimen (string)


## CustomDocumentSubmissionStatusDescription (object)

+ label (string)
+ name (string)
+ value (string)


## TimeClock (object)

+ company (Company)
+ name (string)
+ serial_number (string)


## RootQueryType (object)

+ address (Address)
+ banks (Bank)
+ cities (City)
+ company (Company)
+ countries (Country)
+ enum_descriptions (EnumDescriptions)
+ journey_templates (JourneyTemplate)
+ period (Period)
+ periods (Period)
+ profile (Profile)
+ profile_by_username (Profile)
+ raw_afd_entries (RawAfdEntry)
+ states (State)
+ time_clock_info (KairosTimeClock)
+ viewer (Viewer)


## ProfileCustomFieldsAssocPayload (object)

+ profile (Profile)


## JourneyNonWorkingDay (object)

+ type (string)


## DocumentMaritalStatusUpsertPayload (object)

+ marital_status (object)
+ profile (Profile)


## NationalityDescription (object)

+ label (string)
+ name (string)
+ value (string)


## CompanyExternalAssociations (object)

+ dimep_kairos (DimepKairosCompanyExternalAssociations)
+ dominio (DominioCompanyExternalAssociations)


## Workday (object)

+ absences (Absence)
+ absences_time_in_minutes (number)
+ adjustment_version (number)
+ can_be_approved (boolean)
+ comments (Thread)
+ entries (WorkdayEntry)
+ entries_positions (EntryPosition)
+ entries_summary (EntriesSummary)
+ history (WorkdayHistory)
+ id (string) -- id
+ is_holiday (boolean)
+ is_in_workload (boolean)
+ is_vacation (boolean)
+ next_pending_manager_review (Workday)
+ next_pending_user_review (Workday)
+ overtime (boolean)
+ reference_date (string) -- date
+ status (string)
+ summary_message (string)
+ time_balance_in_minutes (number)
+ undertime (boolean)
+ viewer_can_adjust (boolean)
+ viewer_can_approve (boolean)
+ work_period (ProfileWorkPeriod)
+ workload (WorkdayWorkload)


## DocumentPis (object)

+ attachments (DocumentPisAttachments)
+ number (string)
+ scan_date (string) -- date
+ scanned_fields (string)


## PaystubFilePage (object)

+ id (string) -- id


## State (object)

+ code (string)
+ country (Country)
+ id (string) -- id
+ name (string)


## DocumentRgCpfOcrProgressPayload (object)

+ cpf (DocumentCpf)
+ rg (DocumentRg)


## JourneyFlexConfig (object)

+ group_id (string) -- id
+ id (string) -- id
+ intervals_in_minutes (number)
+ name (string)
+ workload_boundaries (WorkloadBoundaries)
+ workload_in_minutes (number)


## StepMessage (object)

+ steps (Steps)
+ title (string)


## DateTimeEntry (object)

+ end (DateTime)
+ start (DateTime)


## YearMonth (object)

+ month (string) -- month
+ year (number)


## WorkloadNuclearDescription (object)

+ id (string) -- id
+ interval_duration_in_minutes (number)
+ load_in_minutes (number)
+ num_intervals (number)
+ outer_checkin (string) -- time
+ outer_checkout (string) -- time
+ tolerance_in_minutes (number)
+ weekdays (string)


## WorkPeriodAcceptAllReply (object)

+ done (WorkPeriodFilterResult)
+ fail_absences (Absence)
+ fail_workdays (Workday)


## UploadInfo (object)

+ field_name (string)
+ handle (string)


## MaritalStatusDescription (object)

+ label (string)
+ name (string)
+ value (string)


## VerificationStatusDescription (object)

+ label (string)
+ name (string)
+ value (string)


## CustomDocumentSubmission (object)

+ custom_documents (CustomDocument)
+ id (string) -- id
+ inserted_at (string) -- naivedatetime
+ kits (Kit)
+ status (string)


## ProfileAccessSituationDescription (object)

+ label (string)
+ name (string)
+ value (string)


## CustomDocumentSubmissionSendingTypeDescription (object)

+ label (string)
+ name (string)
+ value (string)


## DocumentCamAttachments (object)

+ front_image (Attachment)


## TurnoverAggregation (object)

+ bucket_department (Identifier)
+ turnover_classic (number)
+ turnover_involuntary (number)
+ turnover_voluntary (number)
+ year_month (YearMonth)


## ProfileBenefitStatusDescription (object)

+ label (string)
+ name (string)
+ value (string)


## Onboarding (object)

+ progress (Progress)


## WorkPeriodStatusDescription (object)

+ label (string)
+ name (string)
+ value (string)


## MealAllowanceProvider (object)

+ name (string)


## Contact (object)

+ id (string) -- id
+ label (string)
+ profile (object) -- Profile
+ type (string)
+ value (string)
+ verification_status (string)
+ verified (boolean)


## Billing (object)

+ history (object)
+ payment (Payment)
+ plan (string)
+ plan_identifier (string)


## ContactTypeDescription (object)

+ label (string)
+ name (string)
+ value (string)


## WorkPeriodFilterResult (object)

+ absences (Absence)
+ profile (Profile)
+ time_balance_in_minutes (number)
+ workdays (Workday)


## WorkPeriodListView (object)

+ end_on (string) -- date
+ id (string) -- id
+ overview (WorkPeriodListOverview)
+ start_on (string) -- date
+ status (string)


## CustomCompanyIntegration (object)

+ active (boolean)
+ associable_fields (IntegrationField)
+ company (Company)
+ counts (IntegrationCount)
+ custom_integration (CustomIntegration)
+ description (string)
+ fields (IntegrationField)
+ name (string)
+ type (string)


## Attachment (object)

+ name (string)
+ object_id (string)
+ raw_url (string)
+ thumbnail (Thumbnail)


## ProfileMealAllowance (object)

+ chosen (MealAllowance)
+ status (string)


## AbsenceStatusDescription (object)

+ label (string)
+ name (string)
+ value (string)


## ProfileChildCare (object)

+ chosen (ChildCare)
+ status (string)


## WorkPeriodSubscriptionOverviewWithSummaries (object)

+ overview (WorkPeriodSubscriptionOverview)
+ summaries (WorkPeriodSubscriptionProfile)


## ProfilePhone (object)

+ branch (string)
+ business (string)
+ personal (string)


## WorkPeriodFilterResults (object)

+ results (WorkPeriodFilterResult)
+ total_hits (number)


## BusinessContact (object)

+ branch (string)
+ email (string)
+ mobile (string)
+ phone (string)
+ profile (object) -- Profile
+ updated_contacts (string)


## ProfileWorkPeriodOverview (object)

+ time_balance_in_minutes (number)
+ workdays_missed_count (number)
+ workdays_pending_approval_count (number)
+ workdays_pending_review_count (number)


## OriginalEntries (object)

+ datetime (string) -- naivedatetime
+ removed (boolean)


## AggregationBucketMissing (object)

+ id (string) -- id
+ name (string)


## Account (object)

+ role (Role)
+ roles (Role)


## CompanyBenefits (object)

+ child_cares (ChildCare)
+ dental_insurances (DentalInsurance)
+ health_insurances (HealthInsurance)
+ life_insurances (LifeInsurance)
+ meal_allowances (MealAllowance)
+ transports (Transport)


## DocumentCpfAttachments (object)

+ front_image (Attachment)


## Turnover (object)

+ dataset (TurnoverAggregation)
+ known_departments (Identifier)


## DocumentCnhUpsertPayload (object)

+ cnh (object)
+ profile (Profile)


## WeekdayDescription (object)

+ label (string)
+ name (string)
+ value (string)


## IntegrationField (object)

+ counts (IntegrationCount)
+ incomplete_objects (object)
+ name (string)
+ type (string)


## CustomIntegrationExport (object)

+ custom_integration (CustomIntegration)
+ file_path (string)
+ id (string) -- id
+ incomplete_profiles (IncompleteProfile)
+ integration (object)
+ profiles (Profile)


## WorkPeriodSubscriptionOverview (object)

+ profiles_count (number)
+ profiles_done_count (number)
+ profiles_on_offboard_count (number)
+ profiles_on_vacation_count (number)
+ profiles_pending_count (number)
+ profiles_with_absences_done_count (number)
+ profiles_with_absences_pending_count (number)
+ profiles_with_workdays_done_count (number)
+ profiles_with_workdays_pending_count (number)
+ time_balance_in_minutes (number)


## DocumentRgUpsertPayload (object)

+ profile (Profile)
+ rg (DocumentRg)


## Token (object)

+ id (string) -- id
+ token (string) -- id


## DocumentRg (object)

+ attachments (DocumentRgAttachments)
+ is_validation_ongoing (boolean)
+ issue_date (string) -- date
+ issuer (string)
+ number (string)
+ scan_date (string) -- date
+ scanned_fields (string)
+ state (State)
+ verification_state (DocumentRgVerificationState)


## Progress (object)

+ completed (number)
+ total (number)


## WorkPeriodSubscriptionOverviewByManager (object)

+ manager (Profile)
+ overview (WorkPeriodSubscriptionOverview)
+ summaries (WorkPeriodSubscriptionProfile)


## TemplateDayTypeDescription (object)

+ label (string)
+ name (string)
+ value (string)


## IncompleteProfiles (object)

+ results (WorkPeriodIncompleteProfile)
+ total_hits (number)


## RawAfdEntry (object)

+ datetime (string) -- naivedatetime
+ pis (string)


## Error (object)

+ key (string)
+ msg (string)


## WorkdayHistory (object)

+ what (string)
+ when (string) -- naivedatetime
+ who (PublicProfile)


## AbsentDocument (object)

+ nonexistent (boolean)


## CustomIntegration (object)

+ company (Company)
+ fields (CustomIntegrationField)
+ id (string) -- id


## Country (object)

+ code (string)
+ id (string) -- id
+ name (string)


## Headcount (object)

+ age (EnumAggregation)
+ count (number)
+ department (EnumAggregation)
+ education_degree (EnumAggregation)
+ employment_contract (EnumAggregation)
+ gender (EnumAggregation)
+ marital_status (EnumAggregation)
+ skin_color (EnumAggregation)
+ year_month (YearMonth)


## XerpaPlanDescription (object)

+ label (string)
+ name (string)
+ value (string)


## PaymentCreditCard (object)

+ due (string) -- date
+ status (string)


## PublicPosition (object)

+ id (string) -- id
+ name (string)


## KairosTimeClock (object)

+ clock_factory_number (string)
+ group_id (string) -- id
+ has_automatic_timeclock_import (boolean)
+ last_timeclock_import (string) -- naivedatetime


## SignatureResult (object)

+ results (WorkPeriodProfile)
+ total_hits (number)


## EducationAttachments (object)

+ certificate (Attachment)